label: Коментарі
description: 'Пошук коментарів та керування ними.'
display:
  default:
    display_title: Базово
    display_options:
      title: Коментарі
      fields:
        comment_bulk_form:
          action_title: Дія
        subject:
          label: Тема
          separator: ', '
        uid:
          separator: ', '
        name:
          label: Автор
          separator: ', '
        entity_id:
          label: Опубліковане
          separator: ', '
        changed:
          label: Оновлено
          separator: ', '
        operations:
          label: Операції
        name_1:
          separator: ', '
      pager:
        options:
          tags:
            next: 'наступна ›'
            previous: '‹ попередня'
            first: '« перша'
            last: 'остання »'
          expose:
            items_per_page_label: 'Елементів на сторінку'
            items_per_page_options_all_label: '- Усе -'
            offset_label: Зміщення
      exposed_form:
        options:
          submit_button: Фільтр
          reset_button_label: Скинути
          exposed_sorts_label: 'Впорядкувати за'
          sort_asc_label: Зрост
          sort_desc_label: Спад
      empty:
        area_text_custom:
          content: 'Коментарі відсутні.'
      filters:
        subject:
          expose:
            label: Тема
        combine:
          expose:
            label: 'Ім’я автора'
        langcode:
          expose:
            label: Мова
      use_more_text: ще
  page_published:
    display_title: 'Опубліковані коментарі'
    display_options:
      display_description: 'Список затверджених коментарів.'
      menu:
        title: Коментарі
        description: 'Коментарі опубліковано'
  page_unapproved:
    display_title: 'Несхвалені коментарі'
    display_options:
      fields:
        comment_bulk_form:
          action_title: Дія
        subject:
          label: Тема
          separator: ', '
        uid:
          separator: ', '
        name:
          label: Автор
          separator: ', '
        entity_id:
          label: Опубліковане
          separator: ', '
        changed:
          label: Оновлено
          separator: ', '
        operations:
          label: Операції
        name_1:
          separator: ', '
      filters:
        subject:
          expose:
            label: Тема
        combine:
          expose:
            label: 'Ім''я автора'
        langcode:
          expose:
            label: Мова
      display_description: 'Список незатверджених коментарів.'
      menu:
        title: 'Несхвалені коментарі'
        description: 'Коментарі не затверджено'
