settings:
  default_submit_button_label: Надіслати
  default_reset_button_label: Скинути
  default_delete_button_label: Видалити
  default_preview_next_button_label: 'Попередній перегляд'
  default_preview_label: 'Попередній перегляд'
  dialog_options:
    narrow:
      title: Вузький
    normal:
      title: Звичайне
    wide:
      title: Широкий
element:
  default_more_title: Ще
