_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  automated_cron: 0
  beetroot_example: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  bootstrap_paragraphs: 0
  breakpoint: 0
  ckeditor: 0
  comment: 0
  config: 0
  contact: 0
  context: 0
  context_ui: 0
  core_event_dispatcher: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  diff: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_layout: 0
  field_ui: 0
  file: 0
  filter: 0
  hook_event_dispatcher: 0
  image: 0
  inline_entity_form: 0
  inline_form_errors: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_draggable: 0
  jquery_ui_droppable: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  jsonapi: 0
  jsonapi_extras: 0
  jsonapi_include: 0
  language: 0
  layout_discovery: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  rdf: 0
  responsive_image: 0
  rest: 0
  restui: 0
  serialization: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  user: 0
  views_ui: 0
  viewsreference: 0
  ds: 1
  pathauto: 1
  ds_extras: 2
  content_translation: 10
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  seven: 0
  bootstrap: 0
  beetroot_example_theme: 0
profile: minimal
