services:
  mysql:
    image: tugboatqa/mariadb:10.5

  php:
    image: tugboatqa/php:8-apache
    default: true
    depends: mysql
    commands:
      # Commands that set up the basic preview infrastructure
      init:
        # Install opcache and mod-rewrite.
        - docker-php-ext-install opcache
        - a2enmod headers rewrite

        # Provide symlinks.
        - ln -snf "${TUGBOAT_ROOT}/web" "${DOCROOT}"
        - ln -snf "${TUGBOAT_ROOT}/config" "${DOCROOT}/../config"
        - ln -snf "${TUGBOAT_ROOT}/files-private" "${DOCROOT}/../files-private"

        # Install drupal with default content
        - composer install --optimize-autoloader --no-interaction
        - vendor/bin/drush site:install --existing-config --db-url=mysql://${MYSQL_USER}:${MYSQL_PASS}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB_NAME} -y
        - drush en beetroot_content -y
        - drush pmu beetroot_content default_content hal -y

      update:
        - cp "${TUGBOAT_ROOT}/.tugboat/settings.local.php" "${DOCROOT}/sites/default/"
        - composer install --optimize-autoloader

        # Set file permissions such that Drupal will not complain
        - chgrp -R www-data "${DOCROOT}/sites/default/files"
        - find "${DOCROOT}/sites/default/files" -type d -exec chmod 2775 {} \;
        - find "${DOCROOT}/sites/default/files" -type f -exec chmod 0664 {} \;

      build:
        - composer install --optimize-autoloader --no-interaction
        - drush deploy -y
