services:
  mysql:
    image: tugboatqa/mariadb:10.5

  php:
    image: tugboatqa/php:8-apache
    default: true
    depends: mysql
    commands:
      # Commands that set up the basic preview infrastructure
      init:
        # Install opcache and mod-rewrite.
        - docker-php-ext-install opcache
        - a2enmod headers rewrite

        # Provide symlinks.
        - ln -snf "${TUGBOAT_ROOT}/web" "${DOCROOT}"
        #- ln -snf "${TUGBOAT_ROOT}/config" "${DOCROOT}/../config"
        - ln -snf "${TUGBOAT_ROOT}/files-private" "${DOCROOT}/../files-private"

        - echo "memory_limit = 512M" >> /usr/local/etc/php/conf.d/my-php.ini
        - export PROJECT_BASE_URL=$TUGBOAT_DEFAULT_SERVICE_URL_HOST
        - export HASH_SALT=$TUGBOAT_REPO_ID

        # Install drupal with default content
        - composer install --optimize-autoloader --no-interaction
        - vendor/bin/drush site:install --existing-config --db-url=mysql://${MYSQL_USER}:${MYSQL_PASS}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB_NAME} -y
        - vendor/bin/drush en beetroot_content -y
        - vendor/bin/drush pmu beetroot_content default_content hal -y

      update:
        - composer install --optimize-autoloader

      build:
        - composer install --optimize-autoloader --no-interaction
        - vendor/bin/drush deploy -y
