beetroot_example.settings:
  type: config_object
  label: 'Beetroot Example Settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enabled'
    imporant_number:
      type: integer
      label: 'Some important number'
    important_text:
      type: string
      label: 'Some text'
