beetroot_example.settings:
  type: config_object
  label: 'Beetroot Example Settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enabled'
    imporant_number:
      type: integer
      label: 'Some important number'
    important_text:
      type: string
      label: 'Some text'

# Schema for the configuration files of the Beetroot Example module.
beetroot_example.text_cleanup.settings:
  type: config_object
  label: 'Beetroot Example settings'
  mapping:
    example:
      type: string
      label: 'Example'
