name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare config
        run: cp .env.dist .env
      - name: Build
        run: make up
      - name: Pre-Install
        run: docker-compose exec -T --user=root php bash -c 'chown -R www-data:www-data /var/www'
      - name: Install
        run: make install
      - name: Test
        run: make test
      - name: Deploy
        run: |
          curl -s -H "Authorization: Bearer $TUGBOAT_TOKEN" -H "Content-Type: application/json" -X POST -d "{\"repo\":\"$TUGBOAT_ID\",\"ref\":\"main\",\"type\":\"branch\"}"  https://api.tugboat.qa/v3/previews
