name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare config
        run: cp .env.dist .env
      - name: Build the stack
        run: make
      - name: Test
        run: make test
